name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "35.219.15.90"
UUID = "9d23b9af-4fe1-4b08-aebf-e49c454dd9e4"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
